### ISSUE TITLE
avoid http requests using tesla mock functions

### ISSUE THREAD

**Issue by rands0n** [wesleimp/vroom-elixir#8]
I've implemented a example on lib called Vuforex https://github.com/rands0n/vuforex/blob/main/test/vuforex_test.exs#L5-L35

This will simply mock the requests with some examples pre-configured.

--

https://hexdocs.pm/tesla/readme.html#testing

**Comment by wesleimp** [comment]
I think it's not the case. If you mock the request, in this case, you will test your own mock and not the API response.

http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/
